[package]
name = "src"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
sha2 = "0.10.0"
hex = "0.3.2"
crypto-hash="0.3.3"